
path: '/content/gdrive/My Drive/YOLO_v8/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: Clear
  1: Snowy
